### ISSUE TITLE
Typings needed

### ISSUE THREAD

**Issue by gorkamolero** [rbaumi/angular2-select#1]
Hello! Trying to use this in a Webpack project. Can't install if I don't have global typings & typescript also installed. Throws an error in my language, which would translate to something like:
`"typings" isn't recognized as a command...`

**Comment by rbaumi** [comment]
You're right... I have always typings & typescript installed globally. I will change the package.json so it runs from $(npm bin).

**Comment by gorkamolero** [comment]
Awesome. Thanks! Please tell me if you did

**Comment by rbaumi** [comment]
Done.
