### ISSUE TITLE
Won't install on Windows

### ISSUE THREAD

**Issue by gorkamolero** [rbaumi/angular2-select#2]
Hey again!

I couldn't npm install on windows, error below. I then opened a VM with Linux and installed perfectly.

Here's the reason: 

> Windows uses % for variables, Bash $ so command $(npm bin) fails.

[Source](https://www.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/)

Error here:

`$ npm install @baumi/angular2-select --save

> @baumi/angular2-select@2.1.11 postinstall C:\Users\gfernandez.molero\Documents...\gcs-seed\node_modules\@baumi\angular2-select
> npm run typings-install
> 
> @baumi/angular2-select@2.1.11 typings-install C:\Users\gfernandez.molero\Documents...\gcs-seed\node_modules\@baumi\angular2-select
> $(npm bin)/typings install

"$" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "typings-install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @baumi/angular2-select@2.1.11 typings-install: `$(npm bin)/typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @baumi/angular2-select@2.1.11 typings-install script '$(npm bin)/typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @baumi/angular2-select package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     $(npm bin)/typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @baumi/angular2-select
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @baumi/angular2-select
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
`

**Comment by rbaumi** [comment]
Updated to newest version with fixed build system. Try now! :)

**Comment by gorkamolero** [comment]
Works like magic. As we say in spanish: Grande!
